version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bigpack
    working_dir: /var/www/html/
    restart: always
    container_name: bigpack
    hostname: bigpack
    ports:
      - 8000:9000
    volumes:
      - ./:/var/www/html/:rw
    networks:
      - server-network

networks:
  server-network:
    external: true